### ISSUE TITLE
Radially attached docking ports won't connect living spaces.

### ISSUE THREAD

**Issue by Jivaii** [codepoetpbowden/ConnectedLivingSpace#60] opened 2015-07-22 01:33 UTC
When attempting to dock two parts of a station together, using stock clamp-o-tron docking ports, the living spaces were not connected together.

Testing against a station that had node attached docking ports, no issues at all, living spaces connected properly. 

Anything attempting to dock to a port that is radially attached will not connect living spaces.

**Comment by PapaJoesSoup** [comment] 2015-07-22 07:09
This is by design and contained in the configurations for the parts.   Surface attachment can be changed by the user by editing the Module Manager configuration for the desired part.  

This is explained in the Wiki here:  
https://github.com/codepoetpbowden/ConnectedLivingSpace/wiki/3.0-Module-Manager-Configuration

Additionally, the next planned release contains the ability to alter the configuration of a part in the VAB/SPH during vessel assembly to improve the convenience of making custom changes.

Closing Issue.

**Closed by PapaJoesSoup** 2015-07-22 07:09 UTC
